<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://pix.com/soap/contract"
           targetNamespace="http://pix.com/soap/contract"
           elementFormDefault="qualified">

    <xs:include schemaLocation="entryKey.xsd"/>

    <xs:complexType name="DeleteEntryKeyRequest">
        <xs:sequence>
            <xs:element name="Signature" type="xs:string"/>
            <xs:element name="Key" type="xs:string"/>
            <xs:element name="Participant" type="xs:string"/>
            <xs:element name="Reason" type="tns:ReasonType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DeleteEntryKeyResponse">
        <xs:sequence>
            <xs:group ref="tns:ResponseCommon"/>
            <xs:element name="Key" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>